version: "3"
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    command: bash -c "/filebrowser config set --branding.name \"jfs\" --branding.files \"/theme"\ --branding.disableExternal && /filebrowser"
    ports:
      - 8080:80
    volumes:
      - /home/jesse/:/srv
      - /home/jesse/docker/filebrowser/database.db:/database.db
      - /home/jesse/docker/filebrowser/.filebrowser.json:/.filebrowser.json
      - /home/jesse/docker/filebrowser/theme:/theme
    user: 1000:1000
    restart: unless-stopped
